ERRCOMM.LS     Robot Name ROBOT 05-JUN-24 16:59:04  

1" 05-JUN-24 11:46:38 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
2" 05-JUN-24 11:13:50 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
3" 05-JUN-24 11:03:06 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
