ERRCOMM.LS     Robot Name ROBOT 27-JUN-24 12:51:58  

1" 27-JUN-24 09:44:20 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
2" 26-JUN-24 09:26:36 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
3" 25-JUN-24 10:34:56 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
4" 25-JUN-24 09:44:26 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
5" 14-JUN-24 09:43:06 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
6" 06-JUN-24 12:37:08 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
