ERRCOMM.LS     Robot Name ROBOT 25-JUN-24 13:22:06  

1" 25-JUN-24 10:34:56 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
2" 25-JUN-24 09:44:26 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
3" 14-JUN-24 09:43:06 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
4" 06-JUN-24 12:37:08 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
