ERRACT.LS      Robot Name ROBOT 26-JUN-24 12:57:22  

470" 26-JUN-24 12:57:16 " SYST-040 Operation mode AUTO Selected             " " SERVO                         00110110" 
471" 26-JUN-24 12:57:16 " SYST-042 DEADMAN defeated                         " " SERVO                         00110110" 
472" 26-JUN-24 12:57:16 " SYST-043 TP disabled in T1/T2 mode                " " STOP.L                        00000110" 
