ERRCOMM.LS     Robot Name ROBOT 22-JUL-24 12:23:26  

1" 22-JUL-24 11:39:36 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
2" 27-JUN-24 09:44:20 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
3" 26-JUN-24 09:26:36 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
4" 25-JUN-24 10:34:56 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
5" 25-JUN-24 09:44:26 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
6" 14-JUN-24 09:43:06 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
7" 06-JUN-24 12:37:08 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
