LOGBOOK.LS     Robot Name ROBOT 22-JUL-24 12:23:26  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'IRVWAITLOG.VR' is saved          
22-JUL-24 12:23 :26
========================================
FILE 'IRVTRAIN.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IRVSNAP.VR' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'IRVSAVIR.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IRVRGTRG.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IRVRGGTP.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
22-JUL-24 12:23 :26
========================================
FILE 'IRVLODIR.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IRVIZDT.VR' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'IRVHOMING.VR' is saved           
22-JUL-24 12:23 :26
========================================
FILE 'IRVGSEXE.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IRVGS2VTRN.VR' is saved          
22-JUL-24 12:23 :26
========================================
FILE 'IRVGS2EXE.VR' is saved           
22-JUL-24 12:23 :26
========================================
FILE 'IRVGETMSR.VR' is saved           
22-JUL-24 12:23 :26
========================================
FILE 'IRVGETMSL.VR' is saved           
22-JUL-24 12:23 :26
========================================
FILE 'IRVFIND.VR' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
22-JUL-24 12:23 :26
========================================
FILE 'IRVCALDATA.VR' is saved          
22-JUL-24 12:23 :26
========================================
FILE 'IRVBKLSH.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IRC_STLABEL.VR' is saved         
22-JUL-24 12:23 :26
========================================
FILE 'IRC_STATUS.VR' is saved          
22-JUL-24 12:23 :26
========================================
FILE 'IRC_MSG.VR' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'IRC_COUNTER.VR' is saved         
22-JUL-24 12:23 :26
========================================
FILE 'IPRNGSHO.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IPRNGSET.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'IPKDMP.ZIP' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'IOSTATUS.CM' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'HTTPKCL.VR' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'HTCOLREC.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'HIST.LS' is saved                
22-JUL-24 12:23 :26
========================================
FILE 'GRAPHICS4D.DG' is saved          
22-JUL-24 12:23 :26
========================================
FILE 'GIGELOG.DG' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'GETDATA.TP' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'GEMDATA.VR' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'FTPLOG.DG' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'FRAMEVAR.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'FLEXUIF.XML' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'FLEXEVENT.DG' is saved           
22-JUL-24 12:23 :26
========================================
FILE 'ETHERNET.DG' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'ERRSYS.LS' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'ERRPWD.LS' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'ERRMOT.LS' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'ERRHIST.LS' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'ERREXT.LS' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'ERRCURR.LS' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'ERRCOMM.LS' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'ERRAPP.LS' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'ERRALL.LS' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'ERRACT.LS' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'EMAIL.DG' is saved               
22-JUL-24 12:23 :26
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
22-JUL-24 12:23 :26
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
22-JUL-24 12:23 :26
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
22-JUL-24 12:23 :26
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
22-JUL-24 12:23 :26
========================================
FILE 'DIOCFGSV.IO' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DF_MOTN0.DF' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DF_LOGI6.DF' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DF_LOGI5.DF' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DF_LOGI4.DF' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DF_LOGI3.DF' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DF_LOGI2.DF' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DF_LOGI1.DF' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DCSVRFY.DG' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'DCSPOS.SV' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'DCSIOC.SV' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'DCSDIFF.DG' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'DCSCHG03.DG' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DCSCHG02.DG' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DCSCHG01.DG' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'CONSLOG.DG' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'COMSET.VR' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
22-JUL-24 12:23 :26
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
22-JUL-24 12:23 :26
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
22-JUL-24 12:23 :26
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
22-JUL-24 12:23 :26
========================================
FILE 'CELLIO.SV' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'CBPARAM.VR' is saved             
22-JUL-24 12:23 :26
========================================
FILE 'BICSETUP.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'BACKDATE.DT' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'ATERRJOB.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
22-JUL-24 12:23 :26
========================================
FILE 'ANTENA.VD' is saved              
22-JUL-24 12:23 :26
========================================
FILE 'AAVMMAIN.VR' is saved            
22-JUL-24 12:23 :26
========================================
FILE '-BCKEDT-.TP' is saved            
22-JUL-24 12:23 :26
========================================
FILE '-BCKED9-.TP' is saved            
22-JUL-24 12:23 :26
========================================
FILE '-BCKED8-.TP' is saved            
22-JUL-24 12:23 :26
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
22-JUL-24 12:23 :24
========================================
FILE 'DROP_DEFEITO_3.LS' is loaded     
22-JUL-24 12:23 :24
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
22-JUL-24 12:23 :24
========================================
FILE 'DROP_DEFEITO_2.LS' is loaded     
22-JUL-24 12:23 :24
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
22-JUL-24 12:23 :24
========================================
FILE 'DROP_DEFEITO_1.LS' is loaded     
22-JUL-24 12:23 :24
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
22-JUL-24 12:23 :24
========================================
FILE 'DROP_SEM_DEFEITO.LS' is loaded   
22-JUL-24 12:23 :24
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
22-JUL-24 12:23 :24
========================================
FILE 'PICKUP_COM_RECEPTOR.LS' is loaded
22-JUL-24 12:23 :24
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
22-JUL-24 12:23 :24
========================================
FILE 'SUMIR_SEM_RECEPTOR.LS' is loaded 
22-JUL-24 12:23 :24
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
22-JUL-24 12:23 :24
========================================
FILE 'SUMIR_FURADA_PRENSA.LS' is loaded
22-JUL-24 12:23 :22
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
22-JUL-24 12:23 :22
========================================
FILE 'PICKUP_PRENSA.LS' is loaded      
22-JUL-24 12:23 :22
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
22-JUL-24 12:23 :22
========================================
FILE 'PLACE_BARRA_PRENSA.LS' is loaded 
22-JUL-24 12:23 :22
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
22-JUL-24 12:23 :22
========================================
FILE 'SUMIR_BARRA_TORNO.LS' is loaded  
22-JUL-24 12:23 :22
========================================
FILE 'PLACE_TORNO.TP' is saved         
22-JUL-24 12:23 :22
========================================
FILE 'PLACE_TORNO.LS' is loaded        
22-JUL-24 12:23 :22
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
22-JUL-24 12:23 :22
========================================
FILE 'PICKUP_BARRA_TORNO.LS' is loaded 
22-JUL-24 12:23 :22
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
22-JUL-24 12:23 :22
========================================
FILE 'PICKUP_BARRA_ESTEIRA.LS' is loade
d                                      
22-JUL-24 12:23 :22
========================================
R E S E T                              
                                       
                              00000000 
22-JUL-24 12:09 :54
========================================
FILE 'ZDLOG.DG' is saved               
22-JUL-24 12:09 :54
========================================
FILE 'WORKCELL4D.XML' is saved         
22-JUL-24 12:09 :54
========================================
FILE 'VTRNDIAG.LS' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'VIMGDIAG.ZIP' is saved           
22-JUL-24 12:09 :54
========================================
FILE 'VDEVDIAG.DAT' is saved           
22-JUL-24 12:09 :54
========================================
FILE 'VCMRINIT.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'VARCHG.XML' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'UPLDFIL.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'UPDTLOG.LS' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'UPDATES.DAT' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'TPSNAP.VR' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'TPGLCFG.XML' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'TPEINS.XML' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'TPACCN.DG' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'TOOLING4D.XML' is saved          
22-JUL-24 12:09 :54
========================================
FILE 'SYSVARS.SV' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'SYSUIF.SV' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'SYSSERVO.SV' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SYSPASS.SV' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'SYSMAST.SV' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'SYSMACRO.SV' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SYSHOST.SV' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'SYSFSAC.SV' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'SYSFRAME.SV' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SWIUPDT.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'SUMMARY.DG' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
22-JUL-24 12:09 :54
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
22-JUL-24 12:09 :54
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
22-JUL-24 12:09 :54
========================================
FILE 'STRREG.VR' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'SRWRTCSV.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SROUTSIG.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SHADOW.DG' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'SENDSYSV.TP' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SENDEVNT.TP' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SENDDATA.TP' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
22-JUL-24 12:09 :54
========================================
FILE 'SECLOG.DG' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'RIPESTAT.DG' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'RIPELOG.DG' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'REQMENU.TP' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'RCMSGLIB.DG' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'RCMERR.DG' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'RCMCFG.XML' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'PSRBWLD.CM' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'POSREG.VR' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'PLACE_TORNO.TP' is saved         
22-JUL-24 12:09 :54
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
22-JUL-24 12:09 :54
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
22-JUL-24 12:09 :54
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
22-JUL-24 12:09 :54
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
22-JUL-24 12:09 :54
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
22-JUL-24 12:09 :54
========================================
FILE 'PICK1_PLACE0.TP' is saved        
22-JUL-24 12:09 :54
========================================
FILE 'PEGA_TORNO.TP' is saved          
22-JUL-24 12:09 :54
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
22-JUL-24 12:09 :54
========================================
FILE 'PALREG.VR' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'ORDERFIL.DAT' is saved           
22-JUL-24 12:09 :54
========================================
FILE 'NUMREG.VR' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'NOTIFY.DG' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'MT7L.DT' is saved                
22-JUL-24 12:09 :54
========================================
FILE 'MIXLOGIC.SV' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'MEMCHECK.DG' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'MAKEDIR.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'MAIN.TP' is saved                
22-JUL-24 12:09 :54
========================================
FILE 'LOGBOOK.LS' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'IRVWAITLOG.VR' is saved          
22-JUL-24 12:09 :54
========================================
FILE 'IRVTRAIN.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IRVSNAP.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'IRVSAVIR.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IRVRGTRG.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IRVRGGTP.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
22-JUL-24 12:09 :54
========================================
FILE 'IRVLODIR.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IRVIZDT.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'IRVHOMING.VR' is saved           
22-JUL-24 12:09 :54
========================================
FILE 'IRVGSEXE.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IRVGS2VTRN.VR' is saved          
22-JUL-24 12:09 :54
========================================
FILE 'IRVGS2EXE.VR' is saved           
22-JUL-24 12:09 :54
========================================
FILE 'IRVGETMSR.VR' is saved           
22-JUL-24 12:09 :54
========================================
FILE 'IRVGETMSL.VR' is saved           
22-JUL-24 12:09 :54
========================================
FILE 'IRVFIND.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
22-JUL-24 12:09 :54
========================================
FILE 'IRVCALDATA.VR' is saved          
22-JUL-24 12:09 :54
========================================
FILE 'IRVBKLSH.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IRC_STLABEL.VR' is saved         
22-JUL-24 12:09 :54
========================================
FILE 'IRC_STATUS.VR' is saved          
22-JUL-24 12:09 :54
========================================
FILE 'IRC_MSG.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'IRC_COUNTER.VR' is saved         
22-JUL-24 12:09 :54
========================================
FILE 'IPRNGSHO.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IPRNGSET.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'IPKDMP.ZIP' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'IOSTATUS.CM' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'HTTPKCL.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'HTCOLREC.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'HIST.LS' is saved                
22-JUL-24 12:09 :54
========================================
FILE 'GRAPHICS4D.DG' is saved          
22-JUL-24 12:09 :54
========================================
FILE 'GIGELOG.DG' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'GETDATA.TP' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'GEMDATA.VR' is saved             
22-JUL-24 12:09 :54
========================================
FILE 'FTPLOG.DG' is saved              
22-JUL-24 12:09 :54
========================================
FILE 'FRAMEVAR.VR' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'FLEXUIF.XML' is saved            
22-JUL-24 12:09 :54
========================================
FILE 'FLEXEVENT.DG' is saved           
22-JUL-24 12:09 :52
========================================
FILE 'ETHERNET.DG' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'ERRSYS.LS' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'ERRPWD.LS' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'ERRMOT.LS' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'ERRHIST.LS' is saved             
22-JUL-24 12:09 :52
========================================
FILE 'ERREXT.LS' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'ERRCURR.LS' is saved             
22-JUL-24 12:09 :52
========================================
FILE 'ERRCOMM.LS' is saved             
22-JUL-24 12:09 :52
========================================
FILE 'ERRAPP.LS' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'ERRALL.LS' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'ERRACT.LS' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'EMAIL.DG' is saved               
22-JUL-24 12:09 :52
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
22-JUL-24 12:09 :52
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
22-JUL-24 12:09 :52
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
22-JUL-24 12:09 :52
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
22-JUL-24 12:09 :52
========================================
FILE 'DIOCFGSV.IO' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DF_MOTN0.DF' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DF_LOGI6.DF' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DF_LOGI5.DF' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DF_LOGI4.DF' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DF_LOGI3.DF' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DF_LOGI2.DF' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DF_LOGI1.DF' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DCSVRFY.DG' is saved             
22-JUL-24 12:09 :52
========================================
FILE 'DCSPOS.SV' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'DCSIOC.SV' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'DCSDIFF.DG' is saved             
22-JUL-24 12:09 :52
========================================
FILE 'DCSCHG03.DG' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DCSCHG02.DG' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'DCSCHG01.DG' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'CONSLOG.DG' is saved             
22-JUL-24 12:09 :52
========================================
FILE 'COMSET.VR' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
22-JUL-24 12:09 :52
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
22-JUL-24 12:09 :52
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
22-JUL-24 12:09 :52
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
22-JUL-24 12:09 :52
========================================
FILE 'CELLIO.SV' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'CBPARAM.VR' is saved             
22-JUL-24 12:09 :52
========================================
FILE 'BICSETUP.VR' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'BACKDATE.DT' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'ATERRJOB.VR' is saved            
22-JUL-24 12:09 :52
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
22-JUL-24 12:09 :52
========================================
FILE 'ANTENA.VD' is saved              
22-JUL-24 12:09 :52
========================================
FILE 'AAVMMAIN.VR' is saved            
22-JUL-24 12:09 :52
========================================
FILE '-BCKEDT-.TP' is saved            
22-JUL-24 12:09 :52
========================================
FILE '-BCKED9-.TP' is saved            
22-JUL-24 12:09 :52
========================================
FILE '-BCKED8-.TP' is saved            
22-JUL-24 12:09 :52
========================================
PREV is pressed                        
22-JUL-24 12:04 :38
========================================
PREV is pressed                        
22-JUL-24 12:04 :32
========================================
F5(STRINGS) is pressed                 
22-JUL-24 12:04 :30
--Screen image--------------------------
                                                                                
COLOCA_MESA_IRV>  LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
COLOCA_MESA_IRVISION\\\\\\\\\\        i1                                        
                                  20/26                                         
  14:                                                                           
  15:  LBL[2]                                                                   
  16:L @PR[18:Colocando_Mesa]                                                   
    :  1000mm/sec CNT75                                                         
    :  Tool_Offset,PR[3:Z_Offset_-100]                                          
    :                                                                           
  17:L  PR[17:Frente_Mesa] 1000mm/sec                                           
    :  CNT75                                                                    
  18:                                                                           
  19:  VISION RUN_FIND                                                          
    :  'ANTENAVERIFICATION'                                                     
  20:  VISION GET_OFFSET                                                        
    :  'ANTENAVERIFICATION' VR[1]                                               
    :  JMP LBL[3]                                                               
  21:                                                                           
  22:  CALL ...                                                                 
  23:                                                                           
  24:  LBL[3]                                                                   
  25:  CALL ...                                                                 
[End]                                                                           
                                                                                
                [ROBOT] [CHOICE]STRINGS                                         
========================================
F4([CHOICE]) is pressed                
22-JUL-24 11:55 :34
--Screen image--------------------------
                                                                                
COLOCA_MESA_IRV>  LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
COLOCA_MESA_IRVISION\\\\\\\\\\        i1                                        
                                  20/26                                         
  14:                                                                           
  15:  LBL[2]                                                                   
  16:L @PR[18:Colocando_Mesa]                                                   
    :  1000mm/sec CNT75                                                         
    :  Tool_Offset,PR[3:Z_Offset_-100]                                          
    :                                                                           
  17:L  PR[17:Frente_Mesa] 1000mm/sec                                           
    :  CNT75                                                                    
  18:                                                                           
  19:  VISION RUN_FIND                                                          
    :  'ANTENAVERIFICATION'                                                     
  20:  VISION GET_OFFSET                                                        
    :  'ANTENAVERIFICATION' VR[1]                                               
    :  JMP LBL[3]                                                               
  21:                                                                           
  22:  CALL ...                                                                 
  23:                                                                           
  24:  LBL[3]                                                                   
  25:  CALL ...                                                                 
[End]                                                                           
                                                                                
                [ROBOT] [CHOICE]STRINGS                                         
========================================
Menu changed ''                        
22-JUL-24 11:53 :56
========================================
ENTER is pressed                       
22-JUL-24 11:53 :56
========================================
Menu changed 'Select'                  
22-JUL-24 11:53 :46
========================================
SELECT is pressed                      
22-JUL-24 11:53 :46
========================================
PREV is pressed                        
22-JUL-24 11:53 :46
========================================
ENTER is pressed                       
22-JUL-24 11:53 :06
========================================
PREV is pressed                        
22-JUL-24 11:52 :48
========================================
PREV is pressed                        
22-JUL-24 11:52 :48
========================================
PREV is pressed                        
22-JUL-24 11:52 :48
========================================
PREV is pressed                        
22-JUL-24 11:52 :48
========================================
PREV is pressed                        
22-JUL-24 11:52 :46
========================================
PREV is pressed                        
22-JUL-24 11:52 :46
========================================
PREV is pressed                        
22-JUL-24 11:52 :46
========================================
Menu changed '*B*'                     
22-JUL-24 11:52 :28
========================================
'Vision Setup' is selected in 'iRVisio
n' MENU flyout                        
22-JUL-24 11:52 :28
========================================
ENTER is pressed                       
22-JUL-24 11:52 :28
========================================
Menu changed ''                        
22-JUL-24 11:40 :26
========================================
ENTER is pressed                       
22-JUL-24 11:40 :24
========================================
Menu changed 'Select'                  
22-JUL-24 11:40 :22
========================================
SELECT is pressed                      
22-JUL-24 11:40 :22
========================================
R E S E T                              
                                       
                              00000000 
22-JUL-24 11:40 :18
========================================
R E S E T                              
                                       
                              00000000 
22-JUL-24 11:40 :18
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
22-JUL-24 11:40 :18
========================================
SYST-045 TP enabled in AUTO mode       
                                       
                                       
STOP.G                        00100110 
22-JUL-24 11:40 :18
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
22-JUL-24 11:40 :18
========================================
Focus changed to 'UTILITIES Hints'     
22-JUL-24 11:40 :18
========================================
R E S E T                              
                                       
                              00000000 
22-JUL-24 11:39 :48
========================================
Menu changed 'UTILITIES Hints'         
22-JUL-24 11:39 :40
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
22-JUL-24 11:39 :38
========================================
R E S E T                              
                                       
                              00000000 
22-JUL-24 11:39 :38
========================================
Power failure recovery                 
22-JUL-24 11:39 :10
========================================
R E S E T                              
                                       
                              00000000 
27-JUN-24 12:52 :02
========================================
FILE 'ZDLOG.DG' is saved               
27-JUN-24 12:52 :02
========================================
FILE 'WORKCELL4D.XML' is saved         
27-JUN-24 12:52 :02
========================================
FILE 'VTRNDIAG.LS' is saved            
27-JUN-24 12:52 :02
========================================
FILE 'VIMGDIAG.ZIP' is saved           
27-JUN-24 12:52 :00
========================================
FILE 'VDEVDIAG.DAT' is saved           
27-JUN-24 12:52 :00
========================================
FILE 'VCMRINIT.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'VARCHG.XML' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'UPLDFIL.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'UPDTLOG.LS' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'UPDATES.DAT' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'TPSNAP.VR' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'TPGLCFG.XML' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'TPEINS.XML' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'TPACCN.DG' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'TOOLING4D.XML' is saved          
27-JUN-24 12:52 :00
========================================
FILE 'SYSVARS.SV' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'SYSUIF.SV' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'SYSSERVO.SV' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SYSPASS.SV' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'SYSMAST.SV' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'SYSMACRO.SV' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SYSHOST.SV' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'SYSFSAC.SV' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'SYSFRAME.SV' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SWIUPDT.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'SUMMARY.DG' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 12:52 :00
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 12:52 :00
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 12:52 :00
========================================
FILE 'STRREG.VR' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'SRWRTCSV.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SROUTSIG.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SHADOW.DG' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'SENDSYSV.TP' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SENDEVNT.TP' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SENDDATA.TP' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
27-JUN-24 12:52 :00
========================================
FILE 'SECLOG.DG' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'RIPESTAT.DG' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'RIPELOG.DG' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'REQMENU.TP' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'RCMSGLIB.DG' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'RCMERR.DG' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'RCMCFG.XML' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'PSRBWLD.CM' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'POSREG.VR' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 12:52 :00
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 12:52 :00
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 12:52 :00
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 12:52 :00
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 12:52 :00
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 12:52 :00
========================================
FILE 'PICK1_PLACE0.TP' is saved        
27-JUN-24 12:52 :00
========================================
FILE 'PEGA_TORNO.TP' is saved          
27-JUN-24 12:52 :00
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
27-JUN-24 12:52 :00
========================================
FILE 'PALREG.VR' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'ORDERFIL.DAT' is saved           
27-JUN-24 12:52 :00
========================================
FILE 'NUMREG.VR' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'NOTIFY.DG' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'MT7L.DT' is saved                
27-JUN-24 12:52 :00
========================================
FILE 'MIXLOGIC.SV' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'MEMCHECK.DG' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'MAKEDIR.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'MAIN.TP' is saved                
27-JUN-24 12:52 :00
========================================
FILE 'LOGBOOK.LS' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'IRVWAITLOG.VR' is saved          
27-JUN-24 12:52 :00
========================================
FILE 'IRVTRAIN.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IRVSNAP.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'IRVSAVIR.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IRVRGTRG.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IRVRGGTP.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
27-JUN-24 12:52 :00
========================================
FILE 'IRVLODIR.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IRVIZDT.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'IRVHOMING.VR' is saved           
27-JUN-24 12:52 :00
========================================
FILE 'IRVGSEXE.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IRVGS2VTRN.VR' is saved          
27-JUN-24 12:52 :00
========================================
FILE 'IRVGS2EXE.VR' is saved           
27-JUN-24 12:52 :00
========================================
FILE 'IRVGETMSR.VR' is saved           
27-JUN-24 12:52 :00
========================================
FILE 'IRVGETMSL.VR' is saved           
27-JUN-24 12:52 :00
========================================
FILE 'IRVFIND.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
27-JUN-24 12:52 :00
========================================
FILE 'IRVCALDATA.VR' is saved          
27-JUN-24 12:52 :00
========================================
FILE 'IRVBKLSH.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IRC_STLABEL.VR' is saved         
27-JUN-24 12:52 :00
========================================
FILE 'IRC_STATUS.VR' is saved          
27-JUN-24 12:52 :00
========================================
FILE 'IRC_MSG.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'IRC_COUNTER.VR' is saved         
27-JUN-24 12:52 :00
========================================
FILE 'IPRNGSHO.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IPRNGSET.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'IPKDMP.ZIP' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'IOSTATUS.CM' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'HTTPKCL.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'HTCOLREC.VR' is saved            
27-JUN-24 12:52 :00
========================================
FILE 'HIST.LS' is saved                
27-JUN-24 12:52 :00
========================================
FILE 'GRAPHICS4D.DG' is saved          
27-JUN-24 12:52 :00
========================================
FILE 'GIGELOG.DG' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'GETDATA.TP' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'GEMDATA.VR' is saved             
27-JUN-24 12:52 :00
========================================
FILE 'FTPLOG.DG' is saved              
27-JUN-24 12:52 :00
========================================
FILE 'FRAMEVAR.VR' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'FLEXUIF.XML' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'FLEXEVENT.DG' is saved           
27-JUN-24 12:51 :58
========================================
FILE 'ETHERNET.DG' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'ERRSYS.LS' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'ERRPWD.LS' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'ERRMOT.LS' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'ERRHIST.LS' is saved             
27-JUN-24 12:51 :58
========================================
FILE 'ERREXT.LS' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'ERRCURR.LS' is saved             
27-JUN-24 12:51 :58
========================================
FILE 'ERRCOMM.LS' is saved             
27-JUN-24 12:51 :58
========================================
FILE 'ERRAPP.LS' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'ERRALL.LS' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'ERRACT.LS' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'EMAIL.DG' is saved               
27-JUN-24 12:51 :58
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
27-JUN-24 12:51 :58
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
27-JUN-24 12:51 :58
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
27-JUN-24 12:51 :58
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
27-JUN-24 12:51 :58
========================================
FILE 'DIOCFGSV.IO' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DF_MOTN0.DF' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DF_LOGI6.DF' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DF_LOGI5.DF' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DF_LOGI4.DF' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DF_LOGI3.DF' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DF_LOGI2.DF' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DF_LOGI1.DF' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DCSVRFY.DG' is saved             
27-JUN-24 12:51 :58
========================================
FILE 'DCSPOS.SV' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'DCSIOC.SV' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'DCSDIFF.DG' is saved             
27-JUN-24 12:51 :58
========================================
FILE 'DCSCHG03.DG' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DCSCHG02.DG' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DCSCHG01.DG' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'CONSLOG.DG' is saved             
27-JUN-24 12:51 :58
========================================
FILE 'COMSET.VR' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
27-JUN-24 12:51 :58
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
27-JUN-24 12:51 :58
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
27-JUN-24 12:51 :58
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
27-JUN-24 12:51 :58
========================================
FILE 'CELLIO.SV' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'CBPARAM.VR' is saved             
27-JUN-24 12:51 :58
========================================
FILE 'BICSETUP.VR' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'BACKDATE.DT' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'ATERRJOB.VR' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
27-JUN-24 12:51 :58
========================================
FILE 'ANTENA.VD' is saved              
27-JUN-24 12:51 :58
========================================
FILE 'AAVMMAIN.VR' is saved            
27-JUN-24 12:51 :58
========================================
FILE '-BCKEDT-.TP' is saved            
27-JUN-24 12:51 :58
========================================
FILE '-BCKED9-.TP' is saved            
27-JUN-24 12:51 :58
========================================
FILE '-BCKED8-.TP' is saved            
27-JUN-24 12:51 :58
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
27-JUN-24 12:51 :56
========================================
FILE 'DROP_DEFEITO_3.LS' is loaded     
27-JUN-24 12:51 :56
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
27-JUN-24 12:51 :56
========================================
FILE 'DROP_DEFEITO_2.LS' is loaded     
27-JUN-24 12:51 :56
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
27-JUN-24 12:51 :56
========================================
FILE 'DROP_DEFEITO_1.LS' is loaded     
27-JUN-24 12:51 :56
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
27-JUN-24 12:51 :56
========================================
FILE 'DROP_SEM_DEFEITO.LS' is loaded   
27-JUN-24 12:51 :56
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 12:51 :56
========================================
FILE 'PICKUP_COM_RECEPTOR.LS' is loaded
27-JUN-24 12:51 :54
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 12:51 :54
========================================
FILE 'SUMIR_SEM_RECEPTOR.LS' is loaded 
27-JUN-24 12:51 :54
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 12:51 :54
========================================
FILE 'SUMIR_FURADA_PRENSA.LS' is loaded
27-JUN-24 12:51 :54
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 12:51 :54
========================================
FILE 'PICKUP_PRENSA.LS' is loaded      
27-JUN-24 12:51 :54
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 12:51 :54
========================================
FILE 'PLACE_BARRA_PRENSA.LS' is loaded 
27-JUN-24 12:51 :54
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 12:51 :54
========================================
FILE 'SUMIR_BARRA_TORNO.LS' is loaded  
27-JUN-24 12:51 :52
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 12:51 :52
========================================
FILE 'PLACE_TORNO.LS' is loaded        
27-JUN-24 12:51 :52
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 12:51 :52
========================================
FILE 'PICKUP_BARRA_TORNO.LS' is loaded 
27-JUN-24 12:51 :52
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 12:51 :52
========================================
FILE 'PICKUP_BARRA_ESTEIRA.LS' is loade
d                                      
27-JUN-24 12:51 :52
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
27-JUN-24 12:51 :34
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
27-JUN-24 12:51 :34
========================================
R E S E T                              
                                       
                              00000000 
27-JUN-24 12:45 :06
========================================
FILE 'ZDLOG.DG' is saved               
27-JUN-24 12:45 :06
========================================
FILE 'WORKCELL4D.XML' is saved         
27-JUN-24 12:45 :06
========================================
FILE 'VTRNDIAG.LS' is saved            
27-JUN-24 12:45 :06
========================================
FILE 'VIMGDIAG.ZIP' is saved           
27-JUN-24 12:45 :06
========================================
FILE 'VDEVDIAG.DAT' is saved           
27-JUN-24 12:45 :06
========================================
FILE 'VCMRINIT.VR' is saved            
27-JUN-24 12:45 :06
========================================
FILE 'VARCHG.XML' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'UPLDFIL.VR' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'UPDTLOG.LS' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'UPDATES.DAT' is saved            
27-JUN-24 12:45 :06
========================================
FILE 'TPSNAP.VR' is saved              
27-JUN-24 12:45 :06
========================================
FILE 'TPGLCFG.XML' is saved            
27-JUN-24 12:45 :06
========================================
FILE 'TPEINS.XML' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'TPACCN.DG' is saved              
27-JUN-24 12:45 :06
========================================
FILE 'TOOLING4D.XML' is saved          
27-JUN-24 12:45 :06
========================================
FILE 'SYSVARS.SV' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'SYSUIF.SV' is saved              
27-JUN-24 12:45 :06
========================================
FILE 'SYSSERVO.SV' is saved            
27-JUN-24 12:45 :06
========================================
FILE 'SYSPASS.SV' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'SYSMAST.SV' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'SYSMACRO.SV' is saved            
27-JUN-24 12:45 :06
========================================
FILE 'SYSHOST.SV' is saved             
27-JUN-24 12:45 :06
========================================
FILE 'SYSFSAC.SV' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'SYSFRAME.SV' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'SWIUPDT.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'SUMMARY.DG' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 12:45 :04
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 12:45 :04
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 12:45 :04
========================================
FILE 'STRREG.VR' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'SRWRTCSV.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'SROUTSIG.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'SHADOW.DG' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'SENDSYSV.TP' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'SENDEVNT.TP' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'SENDDATA.TP' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
27-JUN-24 12:45 :04
========================================
FILE 'SECLOG.DG' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'RIPESTAT.DG' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'RIPELOG.DG' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'REQMENU.TP' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'RCMSGLIB.DG' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'RCMERR.DG' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'RCMCFG.XML' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'PSRBWLD.CM' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'POSREG.VR' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 12:45 :04
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 12:45 :04
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 12:45 :04
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 12:45 :04
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 12:45 :04
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 12:45 :04
========================================
FILE 'PICK1_PLACE0.TP' is saved        
27-JUN-24 12:45 :04
========================================
FILE 'PEGA_TORNO.TP' is saved          
27-JUN-24 12:45 :04
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
27-JUN-24 12:45 :04
========================================
FILE 'PALREG.VR' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'ORDERFIL.DAT' is saved           
27-JUN-24 12:45 :04
========================================
FILE 'NUMREG.VR' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'NOTIFY.DG' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'MT7L.DT' is saved                
27-JUN-24 12:45 :04
========================================
FILE 'MIXLOGIC.SV' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'MEMCHECK.DG' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'MAKEDIR.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'MAIN.TP' is saved                
27-JUN-24 12:45 :04
========================================
FILE 'LOGBOOK.LS' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'IRVWAITLOG.VR' is saved          
27-JUN-24 12:45 :04
========================================
FILE 'IRVTRAIN.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IRVSNAP.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'IRVSAVIR.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IRVRGTRG.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IRVRGGTP.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
27-JUN-24 12:45 :04
========================================
FILE 'IRVLODIR.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IRVIZDT.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'IRVHOMING.VR' is saved           
27-JUN-24 12:45 :04
========================================
FILE 'IRVGSEXE.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IRVGS2VTRN.VR' is saved          
27-JUN-24 12:45 :04
========================================
FILE 'IRVGS2EXE.VR' is saved           
27-JUN-24 12:45 :04
========================================
FILE 'IRVGETMSR.VR' is saved           
27-JUN-24 12:45 :04
========================================
FILE 'IRVGETMSL.VR' is saved           
27-JUN-24 12:45 :04
========================================
FILE 'IRVFIND.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
27-JUN-24 12:45 :04
========================================
FILE 'IRVCALDATA.VR' is saved          
27-JUN-24 12:45 :04
========================================
FILE 'IRVBKLSH.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IRC_STLABEL.VR' is saved         
27-JUN-24 12:45 :04
========================================
FILE 'IRC_STATUS.VR' is saved          
27-JUN-24 12:45 :04
========================================
FILE 'IRC_MSG.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'IRC_COUNTER.VR' is saved         
27-JUN-24 12:45 :04
========================================
FILE 'IPRNGSHO.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IPRNGSET.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'IPKDMP.ZIP' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'IOSTATUS.CM' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'HTTPKCL.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'HTCOLREC.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'HIST.LS' is saved                
27-JUN-24 12:45 :04
========================================
FILE 'GRAPHICS4D.DG' is saved          
27-JUN-24 12:45 :04
========================================
FILE 'GIGELOG.DG' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'GETDATA.TP' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'GEMDATA.VR' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'FTPLOG.DG' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'FRAMEVAR.VR' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'FLEXUIF.XML' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'FLEXEVENT.DG' is saved           
27-JUN-24 12:45 :04
========================================
FILE 'ETHERNET.DG' is saved            
27-JUN-24 12:45 :04
========================================
FILE 'ERRSYS.LS' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'ERRPWD.LS' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'ERRMOT.LS' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'ERRHIST.LS' is saved             
27-JUN-24 12:45 :04
========================================
FILE 'ERREXT.LS' is saved              
27-JUN-24 12:45 :04
========================================
FILE 'ERRCURR.LS' is saved             
27-JUN-24 12:45 :02
========================================
FILE 'ERRCOMM.LS' is saved             
27-JUN-24 12:45 :02
========================================
FILE 'ERRAPP.LS' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'ERRALL.LS' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'ERRACT.LS' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'EMAIL.DG' is saved               
27-JUN-24 12:45 :02
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
27-JUN-24 12:45 :02
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
27-JUN-24 12:45 :02
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
27-JUN-24 12:45 :02
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
27-JUN-24 12:45 :02
========================================
FILE 'DIOCFGSV.IO' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DF_MOTN0.DF' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DF_LOGI6.DF' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DF_LOGI5.DF' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DF_LOGI4.DF' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DF_LOGI3.DF' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DF_LOGI2.DF' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DF_LOGI1.DF' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DCSVRFY.DG' is saved             
27-JUN-24 12:45 :02
========================================
FILE 'DCSPOS.SV' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'DCSIOC.SV' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'DCSDIFF.DG' is saved             
27-JUN-24 12:45 :02
========================================
FILE 'DCSCHG03.DG' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DCSCHG02.DG' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'DCSCHG01.DG' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'CONSLOG.DG' is saved             
27-JUN-24 12:45 :02
========================================
FILE 'COMSET.VR' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
27-JUN-24 12:45 :02
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
27-JUN-24 12:45 :02
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
27-JUN-24 12:45 :02
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
27-JUN-24 12:45 :02
========================================
FILE 'CELLIO.SV' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'CBPARAM.VR' is saved             
27-JUN-24 12:45 :02
========================================
FILE 'BICSETUP.VR' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'BACKDATE.DT' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'ATERRJOB.VR' is saved            
27-JUN-24 12:45 :02
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
27-JUN-24 12:45 :02
========================================
FILE 'ANTENA.VD' is saved              
27-JUN-24 12:45 :02
========================================
FILE 'AAVMMAIN.VR' is saved            
27-JUN-24 12:45 :02
========================================
FILE '-BCKEDT-.TP' is saved            
27-JUN-24 12:45 :02
========================================
FILE '-BCKED9-.TP' is saved            
27-JUN-24 12:45 :02
========================================
FILE '-BCKED8-.TP' is saved            
27-JUN-24 12:45 :02
========================================
FILE '-BCKED2-.TP' is saved            
27-JUN-24 12:45 :02
========================================
R E S E T                              
                                       
                              00000000 
27-JUN-24 12:15 :02
========================================
FILE 'ZDLOG.DG' is saved               
27-JUN-24 12:15 :02
========================================
FILE 'WORKCELL4D.XML' is saved         
27-JUN-24 12:15 :02
========================================
FILE 'VTRNDIAG.LS' is saved            
27-JUN-24 12:15 :02
========================================
FILE 'VIMGDIAG.ZIP' is saved           
27-JUN-24 12:15 :02
========================================
FILE 'VDEVDIAG.DAT' is saved           
27-JUN-24 12:15 :00
========================================
FILE 'VCMRINIT.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'VARCHG.XML' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'UPLDFIL.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'UPDTLOG.LS' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'UPDATES.DAT' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'TPSNAP.VR' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'TPGLCFG.XML' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'TPEINS.XML' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'TPACCN.DG' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'TOOLING4D.XML' is saved          
27-JUN-24 12:15 :00
========================================
FILE 'SYSVARS.SV' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'SYSUIF.SV' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'SYSSERVO.SV' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SYSPASS.SV' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'SYSMAST.SV' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'SYSMACRO.SV' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SYSHOST.SV' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'SYSFSAC.SV' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'SYSFRAME.SV' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SWIUPDT.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'SUMMARY.DG' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 12:15 :00
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 12:15 :00
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 12:15 :00
========================================
FILE 'STRREG.VR' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'SRWRTCSV.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SROUTSIG.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SHADOW.DG' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'SENDSYSV.TP' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SENDEVNT.TP' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SENDDATA.TP' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
27-JUN-24 12:15 :00
========================================
FILE 'SECLOG.DG' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'RIPESTAT.DG' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'RIPELOG.DG' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'REQMENU.TP' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'RCMSGLIB.DG' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'RCMERR.DG' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'RCMCFG.XML' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'PSRBWLD.CM' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'POSREG.VR' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 12:15 :00
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 12:15 :00
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 12:15 :00
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 12:15 :00
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 12:15 :00
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 12:15 :00
========================================
FILE 'PICK1_PLACE0.TP' is saved        
27-JUN-24 12:15 :00
========================================
FILE 'PEGA_TORNO.TP' is saved          
27-JUN-24 12:15 :00
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
27-JUN-24 12:15 :00
========================================
FILE 'PALREG.VR' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'ORDERFIL.DAT' is saved           
27-JUN-24 12:15 :00
========================================
FILE 'NUMREG.VR' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'NOTIFY.DG' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'MT7L.DT' is saved                
27-JUN-24 12:15 :00
========================================
FILE 'MIXLOGIC.SV' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'MEMCHECK.DG' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'MAKEDIR.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'MAIN.TP' is saved                
27-JUN-24 12:15 :00
========================================
FILE 'LOGBOOK.LS' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'IRVWAITLOG.VR' is saved          
27-JUN-24 12:15 :00
========================================
FILE 'IRVTRAIN.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IRVSNAP.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'IRVSAVIR.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IRVRGTRG.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IRVRGGTP.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
27-JUN-24 12:15 :00
========================================
FILE 'IRVLODIR.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IRVIZDT.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'IRVHOMING.VR' is saved           
27-JUN-24 12:15 :00
========================================
FILE 'IRVGSEXE.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IRVGS2VTRN.VR' is saved          
27-JUN-24 12:15 :00
========================================
FILE 'IRVGS2EXE.VR' is saved           
27-JUN-24 12:15 :00
========================================
FILE 'IRVGETMSR.VR' is saved           
27-JUN-24 12:15 :00
========================================
FILE 'IRVGETMSL.VR' is saved           
27-JUN-24 12:15 :00
========================================
FILE 'IRVFIND.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
27-JUN-24 12:15 :00
========================================
FILE 'IRVCALDATA.VR' is saved          
27-JUN-24 12:15 :00
========================================
FILE 'IRVBKLSH.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IRC_STLABEL.VR' is saved         
27-JUN-24 12:15 :00
========================================
FILE 'IRC_STATUS.VR' is saved          
27-JUN-24 12:15 :00
========================================
FILE 'IRC_MSG.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'IRC_COUNTER.VR' is saved         
27-JUN-24 12:15 :00
========================================
FILE 'IPRNGSHO.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IPRNGSET.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'IPKDMP.ZIP' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'IOSTATUS.CM' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'HTTPKCL.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'HTCOLREC.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'HIST.LS' is saved                
27-JUN-24 12:15 :00
========================================
FILE 'GRAPHICS4D.DG' is saved          
27-JUN-24 12:15 :00
========================================
FILE 'GIGELOG.DG' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'GETDATA.TP' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'GEMDATA.VR' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'FTPLOG.DG' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'FRAMEVAR.VR' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'FLEXUIF.XML' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'FLEXEVENT.DG' is saved           
27-JUN-24 12:15 :00
========================================
FILE 'ETHERNET.DG' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'ERRSYS.LS' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'ERRPWD.LS' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'ERRMOT.LS' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'ERRHIST.LS' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'ERREXT.LS' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'ERRCURR.LS' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'ERRCOMM.LS' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'ERRAPP.LS' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'ERRALL.LS' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'ERRACT.LS' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'EMAIL.DG' is saved               
27-JUN-24 12:15 :00
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
27-JUN-24 12:15 :00
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
27-JUN-24 12:15 :00
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
27-JUN-24 12:15 :00
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
27-JUN-24 12:15 :00
========================================
FILE 'DIOCFGSV.IO' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DF_MOTN0.DF' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DF_LOGI6.DF' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DF_LOGI5.DF' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DF_LOGI4.DF' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DF_LOGI3.DF' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DF_LOGI2.DF' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DF_LOGI1.DF' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DCSVRFY.DG' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'DCSPOS.SV' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'DCSIOC.SV' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'DCSDIFF.DG' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'DCSCHG03.DG' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DCSCHG02.DG' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'DCSCHG01.DG' is saved            
27-JUN-24 12:15 :00
========================================
FILE 'CONSLOG.DG' is saved             
27-JUN-24 12:15 :00
========================================
FILE 'COMSET.VR' is saved              
27-JUN-24 12:15 :00
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
27-JUN-24 12:14 :58
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
27-JUN-24 12:14 :58
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
27-JUN-24 12:14 :58
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
27-JUN-24 12:14 :58
========================================
FILE 'CELLIO.SV' is saved              
27-JUN-24 12:14 :58
========================================
FILE 'CBPARAM.VR' is saved             
27-JUN-24 12:14 :58
========================================
FILE 'BICSETUP.VR' is saved            
27-JUN-24 12:14 :58
========================================
FILE 'BACKDATE.DT' is saved            
27-JUN-24 12:14 :58
========================================
FILE 'ATERRJOB.VR' is saved            
27-JUN-24 12:14 :58
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
27-JUN-24 12:14 :58
========================================
FILE 'ANTENA.VD' is saved              
27-JUN-24 12:14 :58
========================================
FILE 'AAVMMAIN.VR' is saved            
27-JUN-24 12:14 :58
========================================
FILE '-BCKEDT-.TP' is saved            
27-JUN-24 12:14 :58
========================================
FILE '-BCKED9-.TP' is saved            
27-JUN-24 12:14 :58
========================================
FILE '-BCKED8-.TP' is saved            
27-JUN-24 12:14 :58
========================================
FILE '-BCKED2-.TP' is saved            
27-JUN-24 12:14 :58
========================================
R E S E T                              
                                       
                              00000000 
27-JUN-24 11:44 :58
========================================
FILE 'ZDLOG.DG' is saved               
27-JUN-24 11:44 :58
========================================
FILE 'WORKCELL4D.XML' is saved         
27-JUN-24 11:44 :58
========================================
FILE 'VTRNDIAG.LS' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'VIMGDIAG.ZIP' is saved           
27-JUN-24 11:44 :58
========================================
FILE 'VDEVDIAG.DAT' is saved           
27-JUN-24 11:44 :58
========================================
FILE 'VCMRINIT.VR' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'VARCHG.XML' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'UPLDFIL.VR' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'UPDTLOG.LS' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'UPDATES.DAT' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'TPSNAP.VR' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'TPGLCFG.XML' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'TPEINS.XML' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'TPACCN.DG' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'TOOLING4D.XML' is saved          
27-JUN-24 11:44 :58
========================================
FILE 'SYSVARS.SV' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'SYSUIF.SV' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'SYSSERVO.SV' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SYSPASS.SV' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'SYSMAST.SV' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'SYSMACRO.SV' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SYSHOST.SV' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'SYSFSAC.SV' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'SYSFRAME.SV' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SWIUPDT.VR' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'SUMMARY.DG' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 11:44 :58
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 11:44 :58
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 11:44 :58
========================================
FILE 'STRREG.VR' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'SRWRTCSV.VR' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SROUTSIG.VR' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SHADOW.DG' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'SENDSYSV.TP' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SENDEVNT.TP' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SENDDATA.TP' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
27-JUN-24 11:44 :58
========================================
FILE 'SECLOG.DG' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'RIPESTAT.DG' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'RIPELOG.DG' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'REQMENU.TP' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'RCMSGLIB.DG' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'RCMERR.DG' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'RCMCFG.XML' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'PSRBWLD.CM' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'POSREG.VR' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 11:44 :58
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 11:44 :58
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 11:44 :58
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 11:44 :58
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 11:44 :58
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 11:44 :58
========================================
FILE 'PICK1_PLACE0.TP' is saved        
27-JUN-24 11:44 :58
========================================
FILE 'PEGA_TORNO.TP' is saved          
27-JUN-24 11:44 :58
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
27-JUN-24 11:44 :58
========================================
FILE 'PALREG.VR' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'ORDERFIL.DAT' is saved           
27-JUN-24 11:44 :58
========================================
FILE 'NUMREG.VR' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'NOTIFY.DG' is saved              
27-JUN-24 11:44 :58
========================================
FILE 'MT7L.DT' is saved                
27-JUN-24 11:44 :58
========================================
FILE 'MIXLOGIC.SV' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'MEMCHECK.DG' is saved            
27-JUN-24 11:44 :58
========================================
FILE 'MAKEDIR.VR' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'MAIN.TP' is saved                
27-JUN-24 11:44 :58
========================================
FILE 'LOGBOOK.LS' is saved             
27-JUN-24 11:44 :58
========================================
FILE 'IRVWAITLOG.VR' is saved          
27-JUN-24 11:44 :56
========================================
FILE 'IRVTRAIN.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IRVSNAP.VR' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'IRVSAVIR.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IRVRGTRG.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IRVRGGTP.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
27-JUN-24 11:44 :56
========================================
FILE 'IRVLODIR.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IRVIZDT.VR' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'IRVHOMING.VR' is saved           
27-JUN-24 11:44 :56
========================================
FILE 'IRVGSEXE.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IRVGS2VTRN.VR' is saved          
27-JUN-24 11:44 :56
========================================
FILE 'IRVGS2EXE.VR' is saved           
27-JUN-24 11:44 :56
========================================
FILE 'IRVGETMSR.VR' is saved           
27-JUN-24 11:44 :56
========================================
FILE 'IRVGETMSL.VR' is saved           
27-JUN-24 11:44 :56
========================================
FILE 'IRVFIND.VR' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
27-JUN-24 11:44 :56
========================================
FILE 'IRVCALDATA.VR' is saved          
27-JUN-24 11:44 :56
========================================
FILE 'IRVBKLSH.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IRC_STLABEL.VR' is saved         
27-JUN-24 11:44 :56
========================================
FILE 'IRC_STATUS.VR' is saved          
27-JUN-24 11:44 :56
========================================
FILE 'IRC_MSG.VR' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'IRC_COUNTER.VR' is saved         
27-JUN-24 11:44 :56
========================================
FILE 'IPRNGSHO.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IPRNGSET.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'IPKDMP.ZIP' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'IOSTATUS.CM' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'HTTPKCL.VR' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'HTCOLREC.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'HIST.LS' is saved                
27-JUN-24 11:44 :56
========================================
FILE 'GRAPHICS4D.DG' is saved          
27-JUN-24 11:44 :56
========================================
FILE 'GIGELOG.DG' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'GETDATA.TP' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'GEMDATA.VR' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'FTPLOG.DG' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'FRAMEVAR.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'FLEXUIF.XML' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'FLEXEVENT.DG' is saved           
27-JUN-24 11:44 :56
========================================
FILE 'ETHERNET.DG' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'ERRSYS.LS' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'ERRPWD.LS' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'ERRMOT.LS' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'ERRHIST.LS' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'ERREXT.LS' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'ERRCURR.LS' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'ERRCOMM.LS' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'ERRAPP.LS' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'ERRALL.LS' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'ERRACT.LS' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'EMAIL.DG' is saved               
27-JUN-24 11:44 :56
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
27-JUN-24 11:44 :56
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
27-JUN-24 11:44 :56
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
27-JUN-24 11:44 :56
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
27-JUN-24 11:44 :56
========================================
FILE 'DIOCFGSV.IO' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DF_MOTN0.DF' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DF_LOGI6.DF' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DF_LOGI5.DF' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DF_LOGI4.DF' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DF_LOGI3.DF' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DF_LOGI2.DF' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DF_LOGI1.DF' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DCSVRFY.DG' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'DCSPOS.SV' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'DCSIOC.SV' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'DCSDIFF.DG' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'DCSCHG03.DG' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DCSCHG02.DG' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'DCSCHG01.DG' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'CONSLOG.DG' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'COMSET.VR' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
27-JUN-24 11:44 :56
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
27-JUN-24 11:44 :56
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
27-JUN-24 11:44 :56
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
27-JUN-24 11:44 :56
========================================
FILE 'CELLIO.SV' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'CBPARAM.VR' is saved             
27-JUN-24 11:44 :56
========================================
FILE 'BICSETUP.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'BACKDATE.DT' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'ATERRJOB.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
27-JUN-24 11:44 :56
========================================
FILE 'ANTENA.VD' is saved              
27-JUN-24 11:44 :56
========================================
FILE 'AAVMMAIN.VR' is saved            
27-JUN-24 11:44 :56
========================================
FILE '-BCKEDT-.TP' is saved            
27-JUN-24 11:44 :56
========================================
FILE '-BCKED9-.TP' is saved            
27-JUN-24 11:44 :56
========================================
FILE '-BCKED8-.TP' is saved            
27-JUN-24 11:44 :56
========================================
FILE '-BCKED2-.TP' is saved            
27-JUN-24 11:44 :56
========================================
R E S E T                              
                                       
                              00000000 
27-JUN-24 11:14 :56
========================================
FILE 'ZDLOG.DG' is saved               
27-JUN-24 11:14 :54
========================================
FILE 'WORKCELL4D.XML' is saved         
27-JUN-24 11:14 :54
========================================
FILE 'VTRNDIAG.LS' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'VIMGDIAG.ZIP' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'VDEVDIAG.DAT' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'VCMRINIT.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'VARCHG.XML' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'UPLDFIL.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'UPDTLOG.LS' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'UPDATES.DAT' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'TPSNAP.VR' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'TPGLCFG.XML' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'TPEINS.XML' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'TPACCN.DG' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'TOOLING4D.XML' is saved          
27-JUN-24 11:14 :54
========================================
FILE 'SYSVARS.SV' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'SYSUIF.SV' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'SYSSERVO.SV' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SYSPASS.SV' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'SYSMAST.SV' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'SYSMACRO.SV' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SYSHOST.SV' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'SYSFSAC.SV' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'SYSFRAME.SV' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SWIUPDT.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'SUMMARY.DG' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 11:14 :54
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 11:14 :54
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 11:14 :54
========================================
FILE 'STRREG.VR' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'SRWRTCSV.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SROUTSIG.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SHADOW.DG' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'SENDSYSV.TP' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SENDEVNT.TP' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SENDDATA.TP' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
27-JUN-24 11:14 :54
========================================
FILE 'SECLOG.DG' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'RIPESTAT.DG' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'RIPELOG.DG' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'REQMENU.TP' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'RCMSGLIB.DG' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'RCMERR.DG' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'RCMCFG.XML' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'PSRBWLD.CM' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'POSREG.VR' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 11:14 :54
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 11:14 :54
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 11:14 :54
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 11:14 :54
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 11:14 :54
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 11:14 :54
========================================
FILE 'PICK1_PLACE0.TP' is saved        
27-JUN-24 11:14 :54
========================================
FILE 'PEGA_TORNO.TP' is saved          
27-JUN-24 11:14 :54
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
27-JUN-24 11:14 :54
========================================
FILE 'PALREG.VR' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'ORDERFIL.DAT' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'NUMREG.VR' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'NOTIFY.DG' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'MT7L.DT' is saved                
27-JUN-24 11:14 :54
========================================
FILE 'MIXLOGIC.SV' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'MEMCHECK.DG' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'MAKEDIR.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'MAIN.TP' is saved                
27-JUN-24 11:14 :54
========================================
FILE 'LOGBOOK.LS' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'IRVWAITLOG.VR' is saved          
27-JUN-24 11:14 :54
========================================
FILE 'IRVTRAIN.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IRVSNAP.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'IRVSAVIR.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IRVRGTRG.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IRVRGGTP.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
27-JUN-24 11:14 :54
========================================
FILE 'IRVLODIR.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IRVIZDT.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'IRVHOMING.VR' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'IRVGSEXE.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IRVGS2VTRN.VR' is saved          
27-JUN-24 11:14 :54
========================================
FILE 'IRVGS2EXE.VR' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'IRVGETMSR.VR' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'IRVGETMSL.VR' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'IRVFIND.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
27-JUN-24 11:14 :54
========================================
FILE 'IRVCALDATA.VR' is saved          
27-JUN-24 11:14 :54
========================================
FILE 'IRVBKLSH.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IRC_STLABEL.VR' is saved         
27-JUN-24 11:14 :54
========================================
FILE 'IRC_STATUS.VR' is saved          
27-JUN-24 11:14 :54
========================================
FILE 'IRC_MSG.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'IRC_COUNTER.VR' is saved         
27-JUN-24 11:14 :54
========================================
FILE 'IPRNGSHO.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IPRNGSET.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'IPKDMP.ZIP' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'IOSTATUS.CM' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'HTTPKCL.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'HTCOLREC.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'HIST.LS' is saved                
27-JUN-24 11:14 :54
========================================
FILE 'GRAPHICS4D.DG' is saved          
27-JUN-24 11:14 :54
========================================
FILE 'GIGELOG.DG' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'GETDATA.TP' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'GEMDATA.VR' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'FTPLOG.DG' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'FRAMEVAR.VR' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'FLEXUIF.XML' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'FLEXEVENT.DG' is saved           
27-JUN-24 11:14 :54
========================================
FILE 'ETHERNET.DG' is saved            
27-JUN-24 11:14 :54
========================================
FILE 'ERRSYS.LS' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'ERRPWD.LS' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'ERRMOT.LS' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'ERRHIST.LS' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'ERREXT.LS' is saved              
27-JUN-24 11:14 :54
========================================
FILE 'ERRCURR.LS' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'ERRCOMM.LS' is saved             
27-JUN-24 11:14 :54
========================================
FILE 'ERRAPP.LS' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'ERRALL.LS' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'ERRACT.LS' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'EMAIL.DG' is saved               
27-JUN-24 11:14 :52
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
27-JUN-24 11:14 :52
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
27-JUN-24 11:14 :52
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
27-JUN-24 11:14 :52
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
27-JUN-24 11:14 :52
========================================
FILE 'DIOCFGSV.IO' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DF_MOTN0.DF' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DF_LOGI6.DF' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DF_LOGI5.DF' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DF_LOGI4.DF' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DF_LOGI3.DF' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DF_LOGI2.DF' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DF_LOGI1.DF' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DCSVRFY.DG' is saved             
27-JUN-24 11:14 :52
========================================
FILE 'DCSPOS.SV' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'DCSIOC.SV' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'DCSDIFF.DG' is saved             
27-JUN-24 11:14 :52
========================================
FILE 'DCSCHG03.DG' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DCSCHG02.DG' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'DCSCHG01.DG' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'CONSLOG.DG' is saved             
27-JUN-24 11:14 :52
========================================
FILE 'COMSET.VR' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
27-JUN-24 11:14 :52
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
27-JUN-24 11:14 :52
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
27-JUN-24 11:14 :52
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
27-JUN-24 11:14 :52
========================================
FILE 'CELLIO.SV' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'CBPARAM.VR' is saved             
27-JUN-24 11:14 :52
========================================
FILE 'BICSETUP.VR' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'BACKDATE.DT' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'ATERRJOB.VR' is saved            
27-JUN-24 11:14 :52
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
27-JUN-24 11:14 :52
========================================
FILE 'ANTENA.VD' is saved              
27-JUN-24 11:14 :52
========================================
FILE 'AAVMMAIN.VR' is saved            
27-JUN-24 11:14 :52
========================================
FILE '-BCKEDT-.TP' is saved            
27-JUN-24 11:14 :52
========================================
FILE '-BCKED9-.TP' is saved            
27-JUN-24 11:14 :52
========================================
FILE '-BCKED8-.TP' is saved            
27-JUN-24 11:14 :52
========================================
FILE '-BCKED2-.TP' is saved            
27-JUN-24 11:14 :52
========================================
R E S E T                              
                                       
                              00000000 
27-JUN-24 10:44 :52
========================================
FILE 'ZDLOG.DG' is saved               
27-JUN-24 10:44 :52
========================================
FILE 'WORKCELL4D.XML' is saved         
27-JUN-24 10:44 :52
========================================
FILE 'VTRNDIAG.LS' is saved            
27-JUN-24 10:44 :52
========================================
FILE 'VIMGDIAG.ZIP' is saved           
27-JUN-24 10:44 :52
========================================
FILE 'VDEVDIAG.DAT' is saved           
27-JUN-24 10:44 :52
========================================
FILE 'VCMRINIT.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'VARCHG.XML' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'UPLDFIL.VR' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'UPDTLOG.LS' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'UPDATES.DAT' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'TPSNAP.VR' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'TPGLCFG.XML' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'TPEINS.XML' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'TPACCN.DG' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'TOOLING4D.XML' is saved          
27-JUN-24 10:44 :50
========================================
FILE 'SYSVARS.SV' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'SYSUIF.SV' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'SYSSERVO.SV' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SYSPASS.SV' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'SYSMAST.SV' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'SYSMACRO.SV' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SYSHOST.SV' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'SYSFSAC.SV' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'SYSFRAME.SV' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SWIUPDT.VR' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'SUMMARY.DG' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 10:44 :50
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 10:44 :50
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 10:44 :50
========================================
FILE 'STRREG.VR' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'SRWRTCSV.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SROUTSIG.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SHADOW.DG' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'SENDSYSV.TP' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SENDEVNT.TP' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SENDDATA.TP' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
27-JUN-24 10:44 :50
========================================
FILE 'SECLOG.DG' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'RIPESTAT.DG' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'RIPELOG.DG' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'REQMENU.TP' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'RCMSGLIB.DG' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'RCMERR.DG' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'RCMCFG.XML' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'PSRBWLD.CM' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'POSREG.VR' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 10:44 :50
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 10:44 :50
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 10:44 :50
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 10:44 :50
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 10:44 :50
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 10:44 :50
========================================
FILE 'PICK1_PLACE0.TP' is saved        
27-JUN-24 10:44 :50
========================================
FILE 'PEGA_TORNO.TP' is saved          
27-JUN-24 10:44 :50
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
27-JUN-24 10:44 :50
========================================
FILE 'PALREG.VR' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'ORDERFIL.DAT' is saved           
27-JUN-24 10:44 :50
========================================
FILE 'NUMREG.VR' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'NOTIFY.DG' is saved              
27-JUN-24 10:44 :50
========================================
FILE 'MT7L.DT' is saved                
27-JUN-24 10:44 :50
========================================
FILE 'MIXLOGIC.SV' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'MEMCHECK.DG' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'MAKEDIR.VR' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'MAIN.TP' is saved                
27-JUN-24 10:44 :50
========================================
FILE 'LOGBOOK.LS' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'IRVWAITLOG.VR' is saved          
27-JUN-24 10:44 :50
========================================
FILE 'IRVTRAIN.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IRVSNAP.VR' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'IRVSAVIR.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IRVRGTRG.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IRVRGGTP.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IRVOVRDANYVP.VR' is saved        
27-JUN-24 10:44 :50
========================================
FILE 'IRVLODIR.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IRVIZDT.VR' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'IRVHOMING.VR' is saved           
27-JUN-24 10:44 :50
========================================
FILE 'IRVGSEXE.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IRVGS2VTRN.VR' is saved          
27-JUN-24 10:44 :50
========================================
FILE 'IRVGS2EXE.VR' is saved           
27-JUN-24 10:44 :50
========================================
FILE 'IRVGETMSR.VR' is saved           
27-JUN-24 10:44 :50
========================================
FILE 'IRVGETMSL.VR' is saved           
27-JUN-24 10:44 :50
========================================
FILE 'IRVFIND.VR' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'IRVDISPLAY4D.VR' is saved        
27-JUN-24 10:44 :50
========================================
FILE 'IRVCALDATA.VR' is saved          
27-JUN-24 10:44 :50
========================================
FILE 'IRVBKLSH.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IRC_STLABEL.VR' is saved         
27-JUN-24 10:44 :50
========================================
FILE 'IRC_STATUS.VR' is saved          
27-JUN-24 10:44 :50
========================================
FILE 'IRC_MSG.VR' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'IRC_COUNTER.VR' is saved         
27-JUN-24 10:44 :50
========================================
FILE 'IPRNGSHO.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IPRNGSET.VR' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'IPKDMP.ZIP' is saved             
27-JUN-24 10:44 :50
========================================
FILE 'IOSTATUS.CM' is saved            
27-JUN-24 10:44 :50
========================================
FILE 'HTTPKCL.VR' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'HTCOLREC.VR' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'HIST.LS' is saved                
27-JUN-24 10:44 :48
========================================
FILE 'GRAPHICS4D.DG' is saved          
27-JUN-24 10:44 :48
========================================
FILE 'GIGELOG.DG' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'GETDATA.TP' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'GEMDATA.VR' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'FTPLOG.DG' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'FRAMEVAR.VR' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'FLEXUIF.XML' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'FLEXEVENT.DG' is saved           
27-JUN-24 10:44 :48
========================================
FILE 'ETHERNET.DG' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'ERRSYS.LS' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'ERRPWD.LS' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'ERRMOT.LS' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'ERRHIST.LS' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'ERREXT.LS' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'ERRCURR.LS' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'ERRCOMM.LS' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'ERRAPP.LS' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'ERRALL.LS' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'ERRACT.LS' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'EMAIL.DG' is saved               
27-JUN-24 10:44 :48
========================================
FILE 'DROP_SEM_DEFEITO.TP' is saved    
27-JUN-24 10:44 :48
========================================
FILE 'DROP_DEFEITO_3.TP' is saved      
27-JUN-24 10:44 :48
========================================
FILE 'DROP_DEFEITO_2.TP' is saved      
27-JUN-24 10:44 :48
========================================
FILE 'DROP_DEFEITO_1.TP' is saved      
27-JUN-24 10:44 :48
========================================
FILE 'DIOCFGSV.IO' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DF_MOTN0.DF' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DF_LOGI6.DF' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DF_LOGI5.DF' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DF_LOGI4.DF' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DF_LOGI3.DF' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DF_LOGI2.DF' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DF_LOGI1.DF' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DCSVRFY.DG' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'DCSPOS.SV' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'DCSIOC.SV' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'DCSDIFF.DG' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'DCSCHG03.DG' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DCSCHG02.DG' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'DCSCHG01.DG' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'CONSLOG.DG' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'COMSET.VR' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'COLOCA_PRENSA.TP' is saved       
27-JUN-24 10:44 :48
========================================
FILE 'COLOCA_MESA_IRVISION.TP' is saved
27-JUN-24 10:44 :48
========================================
FILE 'COLOCA_BASE_IRVISION.TP' is saved
27-JUN-24 10:44 :48
========================================
FILE 'COLOCA_BARRA_TORNO.TP' is saved  
27-JUN-24 10:44 :48
========================================
FILE 'CELLIO.SV' is saved              
27-JUN-24 10:44 :48
========================================
FILE 'CBPARAM.VR' is saved             
27-JUN-24 10:44 :48
========================================
FILE 'BICSETUP.VR' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'BACKDATE.DT' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'ATERRJOB.VR' is saved            
27-JUN-24 10:44 :48
========================================
FILE 'ANTENAVERIFICATION.VD' is saved  
27-JUN-24 10:44 :48
========================================
FILE 'ANTENA.VD' is saved              
27-JUN-24 10:44 :46
========================================
FILE 'AAVMMAIN.VR' is saved            
27-JUN-24 10:44 :46
========================================
FILE '-BCKEDT-.TP' is saved            
27-JUN-24 10:44 :46
========================================
FILE '-BCKED9-.TP' is saved            
27-JUN-24 10:44 :46
========================================
FILE '-BCKED8-.TP' is saved            
27-JUN-24 10:44 :46
========================================
FILE '-BCKED2-.TP' is saved            
27-JUN-24 10:44 :46
========================================
Override 100%                          
27-JUN-24 10:14 :46
========================================
R E S E T                              
                                       
                              00000000 
27-JUN-24 10:14 :46
========================================
FILE 'ZDLOG.DG' is saved               
27-JUN-24 10:14 :44
========================================
FILE 'WORKCELL4D.XML' is saved         
27-JUN-24 10:14 :44
========================================
FILE 'VTRNDIAG.LS' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'VIMGDIAG.ZIP' is saved           
27-JUN-24 10:14 :44
========================================
FILE 'VDEVDIAG.DAT' is saved           
27-JUN-24 10:14 :44
========================================
FILE 'VCMRINIT.VR' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'VARCHG.XML' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'UPLDFIL.VR' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'UPDTLOG.LS' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'UPDATES.DAT' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'TPSNAP.VR' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'TPGLCFG.XML' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'TPEINS.XML' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'TPACCN.DG' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'TOOLING4D.XML' is saved          
27-JUN-24 10:14 :44
========================================
FILE 'SYSVARS.SV' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'SYSUIF.SV' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'SYSSERVO.SV' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SYSPASS.SV' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'SYSMAST.SV' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'SYSMACRO.SV' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SYSHOST.SV' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'SYSFSAC.SV' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'SYSFRAME.SV' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SWIUPDT.VR' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'SUMMARY.DG' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'SUMIR_SEM_RECEPTOR.TP' is saved  
27-JUN-24 10:14 :44
========================================
FILE 'SUMIR_FURADA_PRENSA.TP' is saved 
27-JUN-24 10:14 :44
========================================
FILE 'SUMIR_BARRA_TORNO.TP' is saved   
27-JUN-24 10:14 :44
========================================
FILE 'STRREG.VR' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'SRWRTCSV.VR' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SROUTSIG.VR' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SHADOW.DG' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'SENDSYSV.TP' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SENDEVNT.TP' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SENDDATA.TP' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'SEGURA_BARRA_RECEPTOR.TP' is save
d                                      
27-JUN-24 10:14 :44
========================================
FILE 'SECLOG.DG' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'RIPESTAT.DG' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'RIPELOG.DG' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'REQMENU.TP' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'RCMSGLIB.DG' is saved            
27-JUN-24 10:14 :44
========================================
FILE 'RCMERR.DG' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'RCMCFG.XML' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'PSRBWLD.CM' is saved             
27-JUN-24 10:14 :44
========================================
FILE 'POSREG.VR' is saved              
27-JUN-24 10:14 :44
========================================
FILE 'PLACE_TORNO.TP' is saved         
27-JUN-24 10:14 :44
========================================
FILE 'PLACE_BARRA_PRENSA.TP' is saved  
27-JUN-24 10:14 :44
========================================
FILE 'PICKUP_PRENSA.TP' is saved       
27-JUN-24 10:14 :42
========================================
FILE 'PICKUP_COM_RECEPTOR.TP' is saved 
27-JUN-24 10:14 :42
========================================
FILE 'PICKUP_BARRA_TORNO.TP' is saved  
27-JUN-24 10:14 :42
========================================
FILE 'PICKUP_BARRA_ESTEIRA.TP' is saved
27-JUN-24 10:14 :42
========================================
FILE 'PICK1_PLACE0.TP' is saved        
27-JUN-24 10:14 :42
========================================
FILE 'PEGA_TORNO.TP' is saved          
27-JUN-24 10:14 :42
========================================
FILE 'PEGA_BARRA_ESTEIRA.TP' is saved  
27-JUN-24 10:14 :42
========================================
FILE 'PALREG.VR' is saved              
27-JUN-24 10:14 :42
========================================
FILE 'ORDERFIL.DAT' is saved           
27-JUN-24 10:14 :42
========================================
FILE 'NUMREG.VR' is saved              
27-JUN-24 10:14 :42
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 SO[    3]    ON  -> OFF
Tick:   36674
TB:     1787727742
22-JUL-24 11:40 :18
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   36673
TB:     1787714618
22-JUL-24 11:40 :18
========================================
 SO[    3]    OFF -> ON 
Tick:   36476
TB:     1785633211
22-JUL-24 11:40 :18
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   36475
TB:     1785627425
22-JUL-24 11:40 :18
========================================
 SO[    7]    OFF -> ON 
Tick:   36449
TB:     1785341702
22-JUL-24 11:40 :18
========================================
 UO[    8]    OFF -> ON 
Tick:   36448
TB:     1785336057
22-JUL-24 11:40 :18
========================================
 DI[   25]    OFF -> ON 
 DI[   26]    ON  -> OFF
Tick:   11017
TB:     1517534247
22-JUL-24 11:39 :50
========================================
 DI[   20]    OFF -> ON 
 DI[   21]    OFF -> ON 
 DI[   23]    OFF -> ON 
 DI[   26]    OFF -> ON 
Tick:   10972
TB:     1517065704
22-JUL-24 11:39 :50
========================================
 RI[    2]    OFF -> ON 
Tick:   10970
TB:     1517048791
22-JUL-24 11:39 :50
========================================
 SO[    3]    ON  -> OFF
Tick:   8927
TB:     1495875134
22-JUL-24 11:39 :48
========================================
 UO[    6]    ON  -> OFF
Tick:   8926
TB:     1495866640
22-JUL-24 11:39 :48
========================================
 UO[    2]    OFF -> ON 
Tick:   1051
TB:     1402513408
22-JUL-24 11:39 :40
========================================
 UO[    6]    OFF -> ON 
Tick:   1042
TB:     1402481349
22-JUL-24 11:39 :40
========================================
 DO[   50]    OFF -> ON 
 DO[   51]    OFF -> ON 
Tick:   1038
TB:     1402415312
22-JUL-24 11:39 :40
========================================
 DO[   24]    OFF -> ON 
Tick:   1037
TB:     1402411495
22-JUL-24 11:39 :40
========================================
 SO[    3]    OFF -> ON 
Tick:   1025
TB:     1401331701
22-JUL-24 11:39 :40
========================================
 UI[   33]    OFF
 UI[   34]    OFF
 UO[    1]    OFF
 UO[    2]    OFF
 UO[    3]    OFF
 UO[    4]    OFF
 UO[    5]    OFF
 UO[    6]    OFF
 UO[    7]    OFF
 UO[    8]    OFF
 UO[   17]    OFF
 UO[   18]    OFF
 UO[   19]    OFF
 UO[   20]    OFF
 UO[   21]    OFF
 UO[   22]    OFF
 UO[   23]    OFF
 UO[   24]    OFF
 UO[   33]    OFF
 UO[   34]    OFF
 UO[   35]    OFF
 UO[   36]    OFF
Tick:   1015
TB:     1401303417
22-JUL-24 11:39 :40
========================================
 AI[   23]    0
 AO[    1]    0
 AO[    3]    0
 AO[    3]    0
 AO[    5]    0
 AO[    5]    0
 AO[    7]    0
 UI[    1]    ON 
 UI[    2]    ON 
 UI[    3]    ON 
 UI[    4]    OFF
 UI[    5]    OFF
 UI[    6]    OFF
 UI[    7]    OFF
 UI[    8]    ON 
 UI[   17]    OFF
 UI[   18]    OFF
 UI[   19]    OFF
 UI[   20]    OFF
 UI[   21]    OFF
 UI[   22]    OFF
 UI[   23]    OFF
 UI[   24]    OFF
Tick:   1014
TB:     1401302364
22-JUL-24 11:39 :40
========================================
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   19]    0
 AI[   21]    0
Tick:   1013
TB:     1401284396
22-JUL-24 11:39 :40
========================================
 AI[    3]    0
 AI[    5]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
Tick:   1012
TB:     1401283692
22-JUL-24 11:39 :40
========================================
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 AI[    1]    0
Tick:   1011
TB:     1401283233
22-JUL-24 11:39 :40
========================================
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
Tick:   1010
TB:     1400033574
22-JUL-24 11:39 :38
========================================
SPO[   81]    OFF
SPO[   82]    OFF
SPO[   83]    OFF
SPO[   84]    OFF
SPO[   85]    OFF
SPO[   86]    OFF
SPO[   87]    OFF
SPO[   88]    OFF
SPO[   89]    OFF
SPO[   90]    OFF
SPO[   91]    OFF
SPO[   92]    OFF
SPO[   93]    OFF
SPO[   94]    OFF
SPO[   95]    OFF
SPO[   96]    OFF
SPO[   97]    OFF
SPO[   98]    OFF
SPO[   99]    OFF
SPO[  100]    OFF
SPO[  101]    OFF
SPO[  102]    OFF
SPO[  103]    OFF
SPO[  104]    OFF
SPO[  105]    OFF
SPO[  106]    OFF
SPO[  107]    OFF
SPO[  108]    OFF
SPO[  109]    OFF
SPO[  110]    OFF
SPO[  111]    OFF
SPO[  112]    OFF
SPO[  113]    OFF
SPO[  114]    OFF
SPO[  115]    OFF
SPO[  116]    OFF
SPO[  117]    OFF
SPO[  118]    OFF
SPO[  119]    OFF
SPO[  120]    OFF
SPO[  121]    OFF
SPO[  122]    OFF
SPO[  123]    OFF
SPO[  124]    OFF
SPO[  125]    OFF
SPO[  126]    OFF
SPO[  127]    OFF
SPO[  128]    OFF
SSI[    1]    OFF
SSI[    2]    OFF
SSI[    3]    OFF
SSI[    4]    OFF
SSI[    5]    OFF
SSI[    6]    OFF
SSI[    7]    OFF
SSI[    8]    OFF
SSI[    9]    OFF
SSI[   10]    OFF
SSI[   11]    OFF
SSI[   12]    OFF
SSI[   13]    OFF
SSI[   14]    OFF
SSO[    1]    OFF
SSO[    2]    OFF
SSO[    3]    OFF
SSO[    4]    OFF
SSO[    5]    OFF
SSO[    6]    OFF
SSO[    7]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
Tick:   1009
TB:     1400007060
22-JUL-24 11:39 :38
========================================
SPI[   81]    OFF
SPI[   82]    OFF
SPI[   83]    OFF
SPI[   84]    OFF
SPI[   85]    OFF
SPI[   86]    OFF
SPI[   87]    OFF
SPI[   88]    OFF
SPI[   89]    OFF
SPI[   90]    OFF
SPI[   91]    OFF
SPI[   92]    OFF
SPI[   93]    OFF
SPI[   94]    OFF
SPI[   95]    OFF
SPI[   96]    OFF
SPI[   97]    OFF
SPI[   98]    OFF
SPI[   99]    OFF
SPI[  100]    OFF
SPI[  101]    OFF
SPI[  102]    OFF
SPI[  103]    OFF
SPI[  104]    OFF
SPI[  105]    OFF
SPI[  106]    OFF
SPI[  107]    OFF
SPI[  108]    OFF
SPI[  109]    OFF
SPI[  110]    OFF
SPI[  111]    OFF
SPI[  112]    OFF
SPI[  113]    OFF
SPI[  114]    OFF
SPI[  115]    OFF
SPI[  116]    OFF
SPI[  117]    OFF
SPI[  118]    OFF
SPI[  119]    OFF
SPI[  120]    OFF
SPI[  121]    OFF
SPI[  122]    OFF
SPI[  123]    OFF
SPI[  124]    OFF
SPI[  125]    OFF
SPI[  126]    OFF
SPI[  127]    OFF
SPI[  128]    OFF
SPO[    1]    OFF
SPO[    2]    OFF
SPO[    3]    OFF
SPO[    4]    OFF
SPO[    5]    OFF
SPO[    6]    OFF
SPO[    7]    OFF
SPO[    8]    OFF
SPO[    9]    OFF
SPO[   10]    OFF
SPO[   11]    OFF
SPO[   12]    OFF
SPO[   13]    OFF
SPO[   14]    OFF
SPO[   15]    OFF
SPO[   16]    OFF
SPO[   17]    OFF
SPO[   18]    OFF
SPO[   19]    OFF
SPO[   20]    OFF
SPO[   21]    OFF
SPO[   22]    OFF
SPO[   23]    OFF
SPO[   24]    OFF
SPO[   25]    OFF
SPO[   26]    OFF
SPO[   27]    OFF
SPO[   28]    OFF
SPO[   29]    OFF
SPO[   30]    OFF
SPO[   31]    OFF
SPO[   32]    OFF
SPO[   33]    OFF
SPO[   34]    OFF
SPO[   35]    OFF
SPO[   36]    OFF
SPO[   37]    OFF
SPO[   38]    OFF
SPO[   39]    OFF
SPO[   40]    OFF
SPO[   41]    OFF
SPO[   42]    OFF
SPO[   43]    OFF
SPO[   44]    OFF
SPO[   45]    OFF
SPO[   46]    OFF
SPO[   47]    OFF
SPO[   48]    OFF
SPO[   49]    OFF
SPO[   50]    OFF
SPO[   51]    OFF
SPO[   52]    OFF
SPO[   53]    OFF
SPO[   54]    OFF
SPO[   55]    OFF
SPO[   56]    OFF
SPO[   57]    OFF
SPO[   58]    OFF
SPO[   59]    OFF
SPO[   60]    OFF
SPO[   61]    OFF
SPO[   62]    OFF
SPO[   63]    OFF
SPO[   64]    OFF
SPO[   65]    OFF
SPO[   66]    OFF
SPO[   67]    OFF
SPO[   68]    OFF
SPO[   69]    OFF
SPO[   70]    OFF
SPO[   71]    OFF
SPO[   72]    OFF
SPO[   73]    OFF
SPO[   74]    OFF
SPO[   75]    OFF
SPO[   76]    OFF
SPO[   77]    OFF
SPO[   78]    OFF
SPO[   79]    OFF
SPO[   80]    OFF
Tick:   1008
TB:     1400005972
22-JUL-24 11:39 :38
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    ON 
 SI[    9]    ON 
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
SPI[    1]    OFF
SPI[    2]    OFF
SPI[    3]    OFF
SPI[    4]    OFF
SPI[    5]    OFF
SPI[    6]    OFF
SPI[    7]    OFF
SPI[    8]    OFF
SPI[    9]    OFF
SPI[   10]    OFF
SPI[   11]    OFF
SPI[   12]    OFF
SPI[   13]    OFF
SPI[   14]    OFF
SPI[   15]    OFF
SPI[   16]    OFF
SPI[   17]    OFF
SPI[   18]    OFF
SPI[   19]    OFF
SPI[   20]    OFF
SPI[   21]    OFF
SPI[   22]    OFF
SPI[   23]    OFF
SPI[   24]    OFF
SPI[   25]    OFF
SPI[   26]    OFF
SPI[   27]    OFF
SPI[   28]    OFF
SPI[   29]    OFF
SPI[   30]    OFF
SPI[   31]    OFF
SPI[   32]    OFF
SPI[   33]    OFF
SPI[   34]    OFF
SPI[   35]    OFF
SPI[   36]    OFF
SPI[   37]    OFF
SPI[   38]    OFF
SPI[   39]    OFF
SPI[   40]    OFF
SPI[   41]    OFF
SPI[   42]    OFF
SPI[   43]    OFF
SPI[   44]    OFF
SPI[   45]    OFF
SPI[   46]    OFF
SPI[   47]    OFF
SPI[   48]    OFF
SPI[   49]    OFF
SPI[   50]    OFF
SPI[   51]    OFF
SPI[   52]    OFF
SPI[   53]    OFF
SPI[   54]    OFF
SPI[   55]    OFF
SPI[   56]    OFF
SPI[   57]    OFF
SPI[   58]    OFF
SPI[   59]    OFF
SPI[   60]    OFF
SPI[   61]    OFF
SPI[   62]    OFF
SPI[   63]    OFF
SPI[   64]    OFF
SPI[   65]    OFF
SPI[   66]    OFF
SPI[   67]    OFF
SPI[   68]    OFF
SPI[   69]    OFF
SPI[   70]    OFF
SPI[   71]    OFF
SPI[   72]    OFF
SPI[   73]    OFF
SPI[   74]    OFF
SPI[   75]    OFF
SPI[   76]    OFF
SPI[   77]    OFF
SPI[   78]    OFF
SPI[   79]    OFF
SPI[   80]    OFF
Tick:   1007
TB:     1400004947
22-JUL-24 11:39 :38
