ERRCOMM.LS     Robot Name ROBOT 29-JUL-24 11:36:04  

1" 29-JUL-24 09:35:40 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
2" 29-JUL-24 09:35:14 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
3" 25-JUL-24 10:30:56 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
4" 25-JUL-24 10:30:10 " HOST-028 ZDT URL parse error 101                  " " WARN                          00000000" 
