ERRMOT.LS      Robot Name ROBOT 29-JUL-24 11:36:04  

1" 29-JUL-24 10:15:26 " SRVO-003 Deadman switch released                  " " SERVO                         00110110" 
2" 29-JUL-24 09:35:44 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
3" 25-JUL-24 10:30:58 " SRVO-012 Power failure recovery                   " " WARN                          00000100" 
4" 25-JUL-24 10:30:20 " SRVO-307 HBK close/HBK enabled (G:1)              " " WARN                          00000000" 
